#!/usr/bin/env bash
# Print a Nix derivation for a c-c-statusline release, for babarot/nur-packages.
# Usage: nix-derivation.sh <version> <checksums.txt>
set -euo pipefail

version=$1
checksums=$2

sha() {
  local sum
  sum=$(awk -v f="$1" '$2 == f { print $1 }' "$checksums")
  if [[ -z $sum ]]; then
    echo "no checksum for $1 in $checksums" >&2
    exit 1
  fi
  echo "$sum"
}

cat <<EOF
# This file was generated by c-c-statusline's release workflow. DO NOT EDIT.
{
  lib,
  fetchurl,
  stdenvNoCC,
}:
let
  inherit (stdenvNoCC.hostPlatform) system;
  version = "${version}";
  assets = {
    aarch64-darwin = {
      name = "c-c-statusline-darwin-arm64";
      sha256 = "$(sha c-c-statusline-darwin-arm64)";
    };
    x86_64-darwin = {
      name = "c-c-statusline-darwin-x86_64";
      sha256 = "$(sha c-c-statusline-darwin-x86_64)";
    };
    aarch64-linux = {
      name = "c-c-statusline-linux-arm64";
      sha256 = "$(sha c-c-statusline-linux-arm64)";
    };
    x86_64-linux = {
      name = "c-c-statusline-linux-x86_64";
      sha256 = "$(sha c-c-statusline-linux-x86_64)";
    };
  };
  asset = assets.\${system} or (throw "c-c-statusline: unsupported system \${system}");
in
stdenvNoCC.mkDerivation {
  pname = "c-c-statusline";
  inherit version;

  src = fetchurl {
    url = "https://github.com/babarot/c-c-statusline/releases/download/\${version}/\${asset.name}";
    inherit (asset) sha256;
  };

  dontUnpack = true;
  # deno compile appends the program to the executable; stripping or
  # other fixups would break it
  dontFixup = true;

  installPhase = ''
    install -Dm755 \$src \$out/bin/c-c-statusline
  '';

  meta = {
    description = "A Deno-powered status line for Claude Code CLI";
    homepage = "https://github.com/babarot/c-c-statusline";
    license = lib.licenses.mit;
    mainProgram = "c-c-statusline";
    platforms = builtins.attrNames assets;
    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];
  };
}
EOF
